apiVersion: v1
kind: Template
labels:
  application: insights-ds-correlation-container
  createdBy: template-oshinko-python-spark-build-dc
metadata:
  name: insights-ds-correlation-container
parameters:
- name: GIT_URI
  value: "https://gitlab.cee.redhat.com/shanand/insights-ds-correlation-container.git"
- name: APPLICATION_NAME
  value: "insights-ds-correlation-container"
  required: true
- name: SPARK_CLUSTER_NAME
  value: "spark-cluster"
- name: SPARK_MASTER
  value: "spark://spark-cluster:7077"
- name: CEPH_S3_ACCESS_KEY
  value: "IREC3HIIFZ2WMB9UA9U8"
- name: CEPH_S3_SECRET_KEY
  value: "gETnAsfiC4v5coC91n7ADHjdeAxI53bpC52f8ivA"
- name: CEPH_S3_ENDPOINT
  value: "http://storage-016.infra.prod.upshift.eng.rdu2.redhat.com:8080"
- name: CEPH_S3_CONNECTION_SSL_ENABLED
  value: "false"
- name: CEPH_S3_PATH_STYLE_ACCESS
  value: "True"
- name: CEPH_S3_BUCKET
  value: "DH-DEV-INSIGHTS"
- name: CEPH_S3_PREFIX
  value: "shrey-dev"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    dockerImageRepository: ${APPLICATION_NAME}
    tags:
    - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    resources:
      limits:
        memory: 1Gi
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      git:
        uri: ${GIT_URI}
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        env:
        - name: APP_FILE
          value: 'app.py'
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
        forcePull: true
        from:
          kind: DockerImage
          name: 'docker.io/centos/python-36-centos7:latest'
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APPLICATION_NAME}
  data:
  stringData:
    SPARK_MASTER: "${SPARK_MASTER}"
    CEPH_S3_ACCESS_KEY: "${CEPH_S3_ACCESS_KEY}"
    CEPH_S3_SECRET_KEY: "${CEPH_S3_SECRET_KEY}"
    CEPH_S3_ENDPOINT: "${CEPH_S3_ENDPOINT}"
    CEPH_S3_CONNECTION_SSL_ENABLED: "${CEPH_S3_CONNECTION_SSL_ENABLED}"
    CEPH_S3_PATH_STYLE_ACCESS: "${CEPH_S3_PATH_STYLE_ACCESS}"
    CEPH_S3_BUCKET: "${CEPH_S3_BUCKET}"
    CEPH_S3_PREFIX: "${CEPH_S3_PREFIX}"
