apiVersion: v1
kind: Template

labels:
  application: insights-ds-analysis-worker

metadata:
  name: insights-ds-analysis-worker

parameters:
- name: APPLICATION_NAME
  value: 'insights-ds-analysis-worker'
  required: true
- name: PARAMS
  value: '{"date": "2018-06-01", "parsers": [{"name": "insights_parsers_cpuinfo_cpuinfo", "columns": ["cpu_count"]}, {"name": "insights_parsers_meminfo_meminfo", "columns": ["account"]}], "outfile": "TestAnalysis.json"}'
  required: true

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: ${APPLICATION_NAME}:latest
          imagePullPolicy: Always
          env:
              - name: PARAMS
                value: ${PARAMS}
          envFrom:
            - secretRef:
                name: insights-ds-analysis
        restartPolicy: OnFailure
