apiVersion: v1
kind: Template

labels:
  application: correlation-adhoc1

metadata:
  name: correlation-adhoc1

parameters:
- name: APPLICATION_NAME
  value: 'correlation-adhoc1'
  required: true
- name: IMAGE
  value: docker-registry.default.svc:5000/aiops-dev-insights-ds/correlation-adhoc1:latest
- name: PARAMS
  value: '{"FILE_NAME": "2018-04-11/insights_parsers_cpuinfo_cpuinfo", "COL_NAME": ["vendor", "cpu_count"]}'
  required: true

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: ${IMAGE}
          imagePullPolicy: Always
          env:
              - name: PARAMS
                value: ${PARAMS}
          envFrom:
            - secretRef:
                name: ${APPLICATION_NAME}
        restartPolicy: OnFailure
