apiVersion: v1
kind: Template

labels:
  application: insights-ds-analysis-worker

metadata:
  name: insights-ds-analysis-worker

parameters:
- name: APPLICATION_NAME
  value: 'insights-ds-analysis-worker'
  required: true
- name: PARAMS
  value: PARAMS='{"PARSER_NAME": "2018-04-11/insights_parsers_cpuinfo_cpuinfo", "COL_NAME": [ "vendor","model_number"], "OUTFILE_NAME":"graphs.json"}'
  required: true

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: ${APPLICATION_NAME}:latest
          imagePullPolicy: Always
          env:
              - name: PARAMS
                value: ${PARAMS}
          envFrom:
            - secretRef:
                name: insights-ds-analysis
        restartPolicy: OnFailure
