source ../secret

export CEPH_S3_ACCESS_KEY=$CEPH_S3_ACCESS_KEY
export CEPH_S3_SECRET_KEY=$CEPH_S3_SECRET_KEY
export CEPH_S3_ENDPOINT=$CEPH_S3_ENDPOINT
export CEPH_S3_BUCKET=$CEPH_S3_BUCKET
export PARAMS=$PARAMS
export CEPH_S3_PREFIX=$CEPH_S3_PREFIX

python app.py
