apiVersion: v1
kind: Template
labels:
  application: insights-ds-correlation-container
  createdBy: template-oshinko-python-spark-build-dc
metadata:
  name: insights-ds-correlation-container
parameters:
- name: APPLICATION_NAME
  value: "insights-ds-correlation-container"
  required: true
- name: CEPH_S3_ACCESS_KEY
  value: ""
- name: CEPH_S3_SECRET_KEY
  value: ""
- name: CEPH_S3_ENDPOINT
  value: ""
- name: CEPH_S3_CONNECTION_SSL_ENABLED
  value: ""
- name: CEPH_S3_PATH_STYLE_ACCESS
  value: ""
- name: CEPH_S3_BUCKET
  value: ""
- name: CEPH_S3_PREFIX
  value: ""
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APPLICATION_NAME}
  data:
  stringData:
    CEPH_S3_ACCESS_KEY: "${CEPH_S3_ACCESS_KEY}"
    CEPH_S3_SECRET_KEY: "${CEPH_S3_SECRET_KEY}"
    CEPH_S3_ENDPOINT: "${CEPH_S3_ENDPOINT}"
    CEPH_S3_CONNECTION_SSL_ENABLED: "${CEPH_S3_CONNECTION_SSL_ENABLED}"
    CEPH_S3_PATH_STYLE_ACCESS: "${CEPH_S3_PATH_STYLE_ACCESS}"
    CEPH_S3_BUCKET: "${CEPH_S3_BUCKET}"
    CEPH_S3_PREFIX: "${CEPH_S3_PREFIX}"
